version: "3"

services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
  webapp:
    image: petclinic:4
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
    depends_on: 
      - postgres
