FROM maven:3.9.3-eclipse-temurin-17 AS builder

COPY src /usr/src/app/src
COPY pom.xml /usr/src/app

RUN mvn -f /usr/src/app/pom.xml clean package

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /opt/app
COPY --from=builder /usr/src/app/target/*.jar app.jar
EXPOSE 8080
CMD [ "java", "-Dspring.profiles.active=postgres", "-jar", "app.jar" ]
